### ISSUE TITLE
No vuelve a aparecer el preview de la misma foto al seleccionarla

### ISSUE THREAD

**Issue by CristopherVilla20** [Amigos-con-Cola/AmigosConColaWebERP#45]
Cuando selecciona una foto para el animal y la quito con ❌ y luego la vuelvo a subir ya no aparece el preview.
Además cuando vuelvo a subir la foto sin que aparezca el preview y le doy "GUARDAR" entonces el animal se crea sin foto.
Solo después de dar ❌ y seleccionar otra foto diferente, funciona.

![2024-08-07 20-13-09](https://github.com/user-attachments/assets/0133f96c-27e4-4bc8-af43-288da2b3766c)

**Comment by aloussase** [comment]
https://github.com/user-attachments/assets/cda347f2-3692-4466-972b-0ac0de7d5a3c

A mi si me sale.
